---
stages:
  - lint
  - prep simulation environment
  - oob-mgmt bringup
  - network bringup
  - provision simulation
  - test simulation
  - cleanup simulation

lint:
  stage: lint
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/linter.sh

prep:
  stage: prep simulation environment
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/prep.sh
  only:
    - /^dev.*$/

build-oob-mgmt:
  stage: oob-mgmt bringup
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/bring-up-oob-mgmt.sh
  artifacts:
    expire_in: 1 week
    untracked: true
    paths:
      - simulation_$CI_PROJECT_NAME/
  only:
    refs:
      - /^dev.*/

build-network:
  stage: network bringup
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/bring-up-network.sh
  artifacts:
    expire_in: 1 week
    untracked: true
    paths:
      - simulation_$CI_PROJECT_NAME/
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-oob-mgmt

provision-netq:
  stage: network bringup
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/provision-opta.sh
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-oob-mgmt

provision:
  stage: provision simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/provision-sim-outside.sh
  only:
    - /^dev.*$/
  dependencies:
    - build-network

test-from-oob-server:
  stage: test simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/test-sim-outside-oob.sh
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-network

test-from-netq-ts:
  stage: test simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/test-sim-outside-netq.sh
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-network

cleanup:
  stage: cleanup simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/cleanup.sh
  only:
    - /^dev.*$/
  dependencies:
    - build-network
