---
stages:
  - lint
  - prep simulation environment
  - build the simulation
  - provision netq
  - provision the simulation
  - test the simulation
  - cleanup the simulation

lint:
  stage: lint
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/linter.sh

prep:
  stage: prep simulation environment
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/prep.sh
  only:
    - /^dev.*$/

build:
  stage: build the simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    expire_in: 1 week
    untracked: true
    paths:
      - simulation_$CI_PROJECT_NAME/
  script:
    - bash ./cldemo2/ci-common/bring-up-sim.sh
  only:
    - /^dev.*$/

provision-netq:
  stage: provision netq
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/provision-opta.sh
  only:
    - /^dev.*$/
  dependencies:
    - build

provision:
  stage: provision the simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/provision-sim-outside.sh
  only:
    - /^dev.*$/
  dependencies:
    - build

test:
  stage: test the simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/test-sim-outside.sh
  only:
    - /^dev.*$/
  dependencies:
    - build

cleanup:
  stage: cleanup the simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/cleanup.sh
  only:
    - /^dev.*$/
  dependencies:
    - build

