---
stages:
  - lint
  - prep simulation environment
  - oob-mgmt bringup
  - setup inside runners
  - network bringup
  - provision simulation
  - test the simulation
  - cleanup simulation

lint:
  stage: lint
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/linter.sh

prep:
  before_script:
    - PRIVATE_TOKEN="$API_KEY" gitlab-job-guard -c=^dev*
  stage: prep simulation environment
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/prep.sh
  only:
    - /^dev.*$/

build-oob-mgmt:
  stage: oob-mgmt bringup
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/bring-up-oob-mgmt.sh
  artifacts:
    expire_in: 1 week
    untracked: true
    paths:
      - simulation_$CI_PROJECT_NAME/
  only:
    refs:
      - /^dev.*/
    changes:
      - automation/**/*
      - tests/*
      - .gitlab-ci.yml
      - cldemo2

setup-runner-on-netq-ts:
  stage: setup inside runners
  script:
    - cd simulation_$CI_PROJECT_NAME
    - vagrant ssh netq-ts -c "sudo gitlab-runner register --non-interactive --url https://gitlab.com --registration-token $RUNNER_REG_TOKEN --description netq-ts:$CI_JOB_ID --tag-list $CI_PROJECT_NAME:netq-ts --executor shell"
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-oob-mgmt

setup-runner-on-oob-mgmt-server:
  stage: setup inside runners
  script:
    - cd simulation_$CI_PROJECT_NAME
    - vagrant ssh oob-mgmt-server -c "sudo gitlab-runner register --non-interactive --url https://gitlab.com --registration-token $RUNNER_REG_TOKEN --description oob-mgmt-server:$CI_JOB_ID --tag-list $CI_PROJECT_NAME:oob-mgmt --executor shell"
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-oob-mgmt

build-network:
  stage: network bringup
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/bring-up-network.sh
  artifacts:
    expire_in: 1 week
    untracked: true
    paths:
      - simulation_$CI_PROJECT_NAME/
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-oob-mgmt

provision-netq:
  stage: network bringup
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/provision-opta.sh
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-oob-mgmt
  tags:
    - dc_configs_vxlan_evpnsym:netq-ts

provision:
  stage: provision simulation
  script:
    - export ANSIBLE_FORCE_COLOR=true
    - cd automation
    - ansible-playbook playbooks/deploy.yml -i inventories/pod1 --diff
  only:
    - /^dev.*$/
  tags:
    - dc_configs_vxlan_evpnsym:oob-mgmt
  dependencies:
    - build-network

test-from-oob-server:
  stage: test the simulation
  script:
    - bash ./tests/oob-server-tests.sh
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-network
  tags:
    - dc_configs_vxlan_evpnsym:oob-mgmt

test-from-netq-ts:
  stage: test the simulation
  script:
    - bash ./tests/netq-ts-tests.sh
  only:
    refs:
      - /^dev.*/
  dependencies:
    - build-network
  tags:
    - dc_configs_vxlan_evpnsym:netq-ts

cleanup:
  stage: cleanup simulation
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ./cldemo2/ci-common/cleanup.sh
  only:
    - /^dev.*$/
  dependencies:
    - build-network
