#!/bin/bash

netq decommission oob-mgmt-switch
netq decommission oob-mgmt-server
netq decommission netq-ts
netq decommission rtr01
netq decommission rtr02
netq decommission exit01
netq decommission exit02
netq decommission super01
netq decommission super02
netq decommission super03
netq decommission super04
netq decommission spine01
netq decommission spine02
netq decommission spine03
netq decommission spine04
netq decommission spine05
netq decommission spine06
netq decommission spine07
netq decommission spine08
netq decommission fw1
netq decommission fw2
netq decommission fw3
netq decommission fw4
netq decommission leaf01
netq decommission leaf02
netq decommission leaf03
netq decommission leaf04
netq decommission leaf05
netq decommission leaf06
netq decommission leaf07
netq decommission leaf08
netq decommission service01
netq decommission service02
netq decommission service03
netq decommission service04
netq decommission server01
netq decommission server02
netq decommission server03
netq decommission server04
netq decommission server05
netq decommission server06
netq decommission server07
netq decommission server08
netq decommission server09
netq decommission server10
netq decommission server11
netq decommission server12
netq decommission server13
netq decommission server14
netq decommission server15
netq decommission server16
netq decommission server17
netq decommission server18
netq decommission server19
netq decommission server20

