---
- name: Configure FRR daemons file
  template:
    src: daemons.j2
    dest: /etc/frr/daemons
  notify:
    - restart frr

- name: Configure FRR
  template:
    src: "frr_{{switch_role}}.conf.j2"
    dest: /etc/frr/frr.conf
    validate: vtysh -f %s --dryrun
  notify:
    - reload frr

- name: Sysctl 5-tuple hashing
  sysctl:
    name: net.ipv4.fib_multipath_hash_policy
    value: 1
    state: present
    reload: yes

- meta: flush_handlers
